version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          name: "Checking Node and Npm Versions"
          command: |
            node --version
            npm --version

