version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: "Checking Node and Npm Versions"
          command: |
            node --version
            npm --version
      - run:
          name: "INSTALL"
          command: |
            npm i

      - run:
          name: "TEST"
          command: |
            npm run test
